In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

In [12]:
data = np.array([[25,50000,2],[30,80000,1],[20,30000,1],[40,90000,2],
                [45,75000,1]])
labels = np.array([2,1,1,2,1]) # 0:low 1:medium 2:high

In [13]:
X_train,X_test,y_train,y_test = train_test_split(data,labels,test_size=0.2,random_state = 42)
X_train,X_test

(array([[   45, 75000,     1],
        [   20, 30000,     1],
        [   25, 50000,     2],
        [   40, 90000,     2]]),
 array([[   30, 80000,     1]]))

In [14]:
scaler =  StandardScaler()

In [15]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)
X_train,X_test

(array([[ 1.21267813,  0.59743799, -1.        ],
        [-1.21267813, -1.35781362, -1.        ],
        [-0.72760688, -0.4888129 ,  1.        ],
        [ 0.72760688,  1.24918853,  1.        ]]),
 array([[0., 0., 0.]]))

In [16]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [17]:
accuracy = knn.score(X_test,y_test)
accuracy


0.0

In [21]:
user_in = np.array([[10,90000,2]])
user_input_scaled = scaler.transform(user_in)
prediction = knn.predict(user_input_scaled)

In [22]:
if prediction[0] == 1:
    print("Product is buy by customer")
else:
    print("Product doesn't buy by customer")

Product doesn't buy by customer
